version: '3'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: "PgAdmin2021!"
    ports:
      - "15432:5432"
    networks:
      - application-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "hugo.moraes@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2021!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    networks:
      - application-network
      
  redis-cache:
    container_name: redis-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwhgsdHAfasda2022
    volumes: 
      - cache:/data      
    networks:
      - application-network  
      
  url-shortner-api:
    build:
      context: .
      dockerfile: api.dockerfile
    image: api/shortner-url
    container_name: url-shortner-api
    links:
      - postgres-db
      - redis-cache
    environment:
      - JDBC_URL=jdbc:postgresql://postgres-db:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
      - redis-cache
    networks:
      - application-network


  
volumes:
  cache:
    driver: local

networks: 
  application-network:
    driver: bridge
